development:
  AWS_ACCESS_KEY_ID: AKIAJAOPVG2YVDOB7YNQ
  AWS_SECRET_ACCESS_KEY: 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

test:
  AWS_ACCESS_KEY_ID: AKIAJAOPVG2YVDOB7YNQ
  AWS_SECRET_ACCESS_KEY: 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

production:
  AWS_ACCESS_KEY_ID: AKIAJAOPVG2YVDOB7YNQ
  AWS_SECRET_ACCESS_KEY: Te6REhiU98Pyp2r029M3MFtpOOnxQrD1GrosVC6eC6e
