default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  host: localhost
  port:

production:
  <<: *default
  database: education-production

development:
  <<: *default
  database: education-development

test:
  <<: *default
  database: education-test
